name: CI
on:
  - push
  - pull_request
jobs:
  build:
    # env:
    #   # DEBUG: 'prisma:*'
    #   # PRISMA_GENERATE_SKIP_AUTOINSTALL: 1
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    name: 'Test on Node ${{ matrix.node }} and ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      # max-parallel: 1
      matrix:
        node:
          - 20
        os:
          - ubuntu-latest
          # - windows-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Setup Node ${{ matrix.node }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node }}'
      - name: 'Install depependencies'
        run: yarn install
      - name: 'Regenerate'
        run: yarn regen
      - name: 'ESLint'
        run: |
          yarn eslint
      - name: 'tscheck'
        run: |
          yarn tscheck
      - name: 'Test'
        run: |
          yarn test:cov -- --bail
      - name: 'Test Build'
        run: |
          yarn build
      - name: 'Compatibilty Check'
        run: |
          yarn compatibilty_check
  release:
    name: 'Release'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node:
          - 20
        os:
          - ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next')
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node }}'
      - name: 'Install depependencies'
        run: yarn install
      - name: 'Build'
        run: yarn build
      - name: 'Release'
        run: |
          yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
